fn main() {
    // Registers this app's two custom commands (set_autostart/get_autostart,
    // src/main.rs) with Tauri's ACL, autogenerating `allow-set-autostart` /
    // `allow-get-autostart` permissions into ./permissions/autogenerated/.
    // Without this, a capability file has no permission identifier to grant
    // and `window.__TAURI__.core.invoke(...)` is refused for every window,
    // including the daemon's own remote page this shell loads.
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(
            tauri_build::AppManifest::new().commands(&["set_autostart", "get_autostart"]),
        ),
    )
    .expect("failed to run tauri-build");
}
